// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKgKVv52RecL0LyiVBY_w_-G-CkZqJquA',
    appId: '1:693556463925:web:308c6605742e26e3fb247c',
    messagingSenderId: '693556463925',
    projectId: 'pos-firebase-20815',
    authDomain: 'pos-firebase-20815.firebaseapp.com',
    storageBucket: 'pos-firebase-20815.firebasestorage.app',
    measurementId: 'G-KNRJL0QN2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8KnzZ9ahEZBgJLxGE_fgC7CNKFg5gW_s',
    appId: '1:693556463925:android:f300dbc0287b447efb247c',
    messagingSenderId: '693556463925',
    projectId: 'pos-firebase-20815',
    storageBucket: 'pos-firebase-20815.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0XTqWf1LxxXrRUIXrCnXOfFdsl_Rd2f4',
    appId: '1:693556463925:ios:961d830d934968f7fb247c',
    messagingSenderId: '693556463925',
    projectId: 'pos-firebase-20815',
    storageBucket: 'pos-firebase-20815.firebasestorage.app',
    iosBundleId: 'com.example.posFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0XTqWf1LxxXrRUIXrCnXOfFdsl_Rd2f4',
    appId: '1:693556463925:ios:961d830d934968f7fb247c',
    messagingSenderId: '693556463925',
    projectId: 'pos-firebase-20815',
    storageBucket: 'pos-firebase-20815.firebasestorage.app',
    iosBundleId: 'com.example.posFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKgKVv52RecL0LyiVBY_w_-G-CkZqJquA',
    appId: '1:693556463925:web:21bb1f60f538efe6fb247c',
    messagingSenderId: '693556463925',
    projectId: 'pos-firebase-20815',
    authDomain: 'pos-firebase-20815.firebaseapp.com',
    storageBucket: 'pos-firebase-20815.firebasestorage.app',
    measurementId: 'G-0KWLYEFSEK',
  );

}